EdmureBlog/EdmureBlog/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^backend/', include('backend.urls')),
    url(r'^', include('web.urls')),
]

EdmureBlog/web/urls.py
from django.conf.urls import url
from .views import home
from .views import account

urlpatterns = [
    url(r'^jsonp.html$', account.jsonp),
    url(r'^login.html$', account.login),
    url(r'^logout.html$', account.logout),
    url(r'^register.html$', account.register),
    url(r'^check_code.html$', account.check_code),
    url(r'^all/(?P<article_type_id>\d+).html$', home.index, name='index'),
    url(r'^(?P<site>\w+).html$', home.home),
    url(r'^(?P<site>\w+)/(?P<condition>((tag)|(date)|(category)))/(?P<val>\w+-*\w*).html$', home.filter),
    url(r'^(?P<site>\w+)/(?P<nid>\d+).html$', home.detail),
    url(r'^', home.index),
]

EdmureBlog/repository/models.py
from django.db import models


class UserInfo(models.Model):
    """
    用户表
    """
    nid = models.BigAutoField(primary_key=True)
    username = models.CharField(verbose_name='用户名', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    avatar = models.ImageField(verbose_name='头像')

    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    fans = models.ManyToManyField(verbose_name='粉丝们',
                                  to='UserInfo',
                                  through='UserFans',
                                  related_name='f',
                                  through_fields=('user', 'follower'))


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客前缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)
    user = models.OneToOneField(to='UserInfo', on_delete=models.CASCADE, to_field='nid')


class UserFans(models.Model):
    """
    互粉关系表
    """
    user = models.ForeignKey(verbose_name='博主', on_delete=models.CASCADE, to='UserInfo', to_field='nid', related_name='users')
    follower = models.ForeignKey(verbose_name='粉丝', on_delete=models.CASCADE, to='UserInfo', to_field='nid', related_name='followers')

    class Meta:
        unique_together = [
            ('user', 'follower'),
        ]


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)

    blog = models.ForeignKey(verbose_name='所属博客', on_delete=models.CASCADE, to='Blog', to_field='nid')


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', on_delete=models.CASCADE, to='Article', to_field='nid')


class UpDown(models.Model):
    """
    文章顶或踩
    """
    article = models.ForeignKey(verbose_name='文章', on_delete=models.CASCADE, to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='赞或踩用户', on_delete=models.CASCADE, to='UserInfo', to_field='nid')
    up = models.BooleanField(verbose_name='是否赞')

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复评论', on_delete=models.CASCADE, to='self', related_name='back', null=True)
    article = models.ForeignKey(verbose_name='评论文章', on_delete=models.CASCADE, to='Article', to_field='nid')
    user = models.ForeignKey(verbose_name='评论者', on_delete=models.CASCADE, to='UserInfo', to_field='nid')


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', on_delete=models.CASCADE, to='Blog', to_field='nid')


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=128)
    summary = models.CharField(verbose_name='文章简介', max_length=255)
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)  #点赞个数
    down_count = models.IntegerField(default=0)  # 踩的个数
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    blog = models.ForeignKey(verbose_name='所属博客', on_delete=models.CASCADE, to='Blog', to_field='nid')
    category = models.ForeignKey(verbose_name='文章类型', on_delete=models.CASCADE, to='Category', to_field='nid', null=True)

    type_choices = [
        (1, "Python"),
        (2, "Linux"),
        (3, "OpenStack"),
        (4, "GoLang"),
    ]

    article_type_id = models.IntegerField(choices=type_choices, default=None)

    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )


class Article2Tag(models.Model):
    article = models.ForeignKey(verbose_name='文章', on_delete=models.CASCADE, to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', on_delete=models.CASCADE, to="Tag", to_field='nid')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

EdmureBlog/web/views/home.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.shortcuts import redirect
from repository import models
from utils.pagination import Pagination
from django.urls import reverse

def index(request, *args, **kwargs):
    """
    博客首页，展示全部博文
    :param request:
    :return:
    """

    article_type_list = models.Article.type_choices

    if kwargs:
        article_type_id = int(kwargs['article_type_id'])
        base_url = reverse('index',kwargs=kwargs)
    else:
        article_type_id = None
        base_url = '/'

    data_count = article_list = models.Article.objects.filter(**kwargs).count()


    page_obj = Pagination(request.GET.get('p'),data_count)
    article_list = models.Article.objects.filter(**kwargs).order_by('-nid')[page_obj.start:page_obj.end]
    page_str = page_obj.page_str(base_url)

    return render(
        request,
        'index.html',
        {
            'article_list': article_list,
            'article_type_id': article_type_id,
            'article_type_list': article_type_list,
            'page_str': page_str,
        }
    )


def home(request, site):
    """
    博主个人首页
    :param request:
    :param site: 博主的网站后缀如：http://xxx.com/wupeiqi.html
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    # date_format(create_time,"%Y-%m")
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    for item in date_list:
        print(item.nid,item.num,item.ctime)
    article_list = models.Article.objects.filter(blog=blog).order_by('-nid').all()

    return render(
        request,
        'home.html',
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list
        }
    )


def filter(request, site, condition, val):
    """
    分类显示
    :param request:
    :param site:
    :param condition:
    :param val:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    if not blog:
        return redirect('/')
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    template_name = "home_summary_list.html"
    if condition == 'tag':
        template_name = "home_title_list.html"
        article_list = models.Article.objects.filter(tags=val, blog=blog).all()
    elif condition == 'category':
        article_list = models.Article.objects.filter(category_id=val, blog=blog).all()
    elif condition == 'date':
        # article_list = models.Article.objects.filter(blog=blog).extra(
        # where=['date_format(create_time,"%%Y-%%m")=%s'], params=[val, ]).all()

        article_list = models.Article.objects.filter(blog=blog).extra(
            where=['strftime("%%Y-%%m",create_time)=%s'], params=[val, ]).all()
        # select * from article where strftime("%Y-%m",create_time)=2017-02
    else:
        article_list = []

    return render(
        request,
        template_name,
        {
            'blog': blog,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
            'article_list': article_list
        }
    )


def detail(request, site, nid):
    """
    博文详细页
    :param request:
    :param site:
    :param nid:
    :return:
    """
    blog = models.Blog.objects.filter(site=site).select_related('user').first()
    tag_list = models.Tag.objects.filter(blog=blog)
    category_list = models.Category.objects.filter(blog=blog)
    date_list = models.Article.objects.raw(
        'select nid, count(nid) as num,strftime("%Y-%m",create_time) as ctime from repository_article group by strftime("%Y-%m",create_time)')

    article = models.Article.objects.filter(blog=blog, nid=nid).select_related('category', 'articledetail').first()
    comment_list = models.Comment.objects.filter(article=article).select_related('reply')
    return render(
        request,
        'home_detail.html',
        {
            'blog': blog,
            'article': article,
            'comment_list': comment_list,
            'tag_list': tag_list,
            'category_list': category_list,
            'date_list': date_list,
        }

    )

EdmureBlog/templates/backend_add_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
        }
    </style>
{% endblock %}

{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">添加文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <form method="POST" action="/backend/add-article.html" novalidate>
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">标题 <span>{{ form.title.errors.0 }}</span></label>
                {{ form.title }}
            </div>
            <div class="form-group">
                <label for="summary">简介 <span>{{ form.summary.errors.0 }}</span></label>
                {{ form.summary }}
            </div>
            <div class="form-group">
                <label for="content">内容 <span>{{ form.content.errors.0 }}</span></label>
                {{ form.content }}
            </div>
            <div class="form-group">
                <label>类型 <span>{{ form.article_type_id.errors.0 }}</span></label>

                <div>
                    {{ form.article_type_id }}
                </div>

            </div>
            <div class="form-group">
                <label>分类 <span>{{ form.category_id.errors.0 }}</span></label>

                <div>
                    {{ form.category_id }}
                </div>
            </div>
            <div class="form-group">
                <label>标签 <span>{{ form.tags.errors.0 }}</span></label>

                <div>
                    {{ form.tags }}
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="保 存">
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        KindEditor.ready(function (K) {
            var editor = K.create('textarea[name="content"]', {
                resizeType: 1
            });
        });
    </script>
{% endblock %}

EdmureBlog/templates/backend_base_info.html
{% extends 'backend_layout.html' %}
{% block css %}
    <style>
        .form-horizontal .control-label {
            padding-top: 7px;
            margin-bottom: 0;
            text-align: right;
        }

        .avatar-container {
            height: 200px;
            width: 200px;
            padding: 2px;
            border: 1px solid #dddddd;
            position: relative;
        }

        .avatar-container img {
            height: 100%;
            width: 100%;
            border: 0;
            overflow: hidden;
        }

        .avatar-container .text {
            text-align: center;
        }

        .avatar-container .img-file {
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            opacity: 0;
            position: absolute;
            z-index: 102;
        }
    </style>
{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">用户管理</a></li>
        <li class="active">用户信息</li>
    </ol>
    <div>

        <div class="row" style="position: relative;">
            <form class="form-horizontal">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-2 control-label">用户名</label>

                        <div class="col-xs-5">
                            <p class="form-control-static">Achilles</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-xs-2 control-label">邮箱</label>

                        <div class="col-xs-5">
                            <p class="form-control-static">njupy@example.com</p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="nickname" class="col-xs-2 control-label">昵称</label>

                        <div class="col-xs-5">
                            <input type="text" class="form-control" id="nickname" placeholder="请输入昵称">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogUrl" class="col-xs-2 control-label">博客地址</label>

                        <div class="col-xs-5">
                            <input type="text" class="form-control" id="blogUrl"
                                   placeholder="如：Achilles,则个人博客为http://www.xxxxx.com/Achilles.html">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogTheme" class="col-xs-2 control-label">博客主题</label>

                        <div class="col-xs-5">
                            <select id="blogTheme" class="form-control">
                                <option>默认主题</option>
                                <option>红色火焰</option>
                                <option>星空爱恋</option>
                                <option>运动健身</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="blogTitle" class="col-xs-2 control-label">博客标题内容</label>

                        <div class="col-xs-8">
                            <textarea id="blogTitle" style="min-height: 100px" class="form-control"
                                      placeholder="简单介绍"></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-offset-2 col-xs-10">
                            <button type="submit" class="btn btn-primary">保 存</button>
                        </div>
                    </div>

                </div>
            </form>
            <div style="position: absolute;" class="col-xs-offset-7 col-xs-5">
                <div class="avatar-container">
                    <iframe style="display: none;" id="upload_iframe" name="upload_iframe"></iframe>
                    <form method="POST" action="/backend/upload-avatar.html" enctype="multipart/form-data"
                          target="upload_iframe">
                        {% csrf_token %}
                        <img id="previewImg" origin="/static/imgs/avatar/123.jpg"
                             src="/static/imgs/avatar/123.jpg"
                             style="border-radius: 0;">

                        <div class="text">点击图片更换(<a href="#">撤销</a>)</div>
                        <input id="avatarImg" name="avatar_img" type="file" class="img-file"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            bindChangeAvatar4();
        });

        function bindChangeAvatar1() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                $('#prevViewImg')[0].src = window.URL.createObjectURL(file_obj)
            })
        }

        function bindChangeAvatar2() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                var reader = new FileReader();
                reader.readAsDataURL(file_obj);
                reader.onload = function (e) {
                    $('#previewImg')[0].src = this.result;
                };
            })
        }

        function bindChangeAvatar3() {
            $('#avatarImg').change(function () {
                var file_obj = $(this)[0].files[0];
                var form = new FormData();
                form.add('img_upload', file_obj);

                $.ajax({
                    url: '',
                    data: form,
                    processData: false,  // tell jQuery not to process the data
                    contentType: false,  // tell jQuery not to set contentType
                    success: function (arg) {

                    }
                })
            })
        }

        function bindChangeAvatar4() {
            $('#avatarImg').change(function () {
                $(this).parent().submit();

                $('#upload_iframe').load(function () {
                    var iframeContents = this.contentWindow.document.body.innerText;
                    iframeContents = JSON.parse(iframeContents);
                    if (iframeContents.status) {
                        $('#previewImg').attr('src', '/' + iframeContents.data);
                    }
                })

            })
        }

    </script>
{% endblock %}

EdmureBlog/templates/backend_category.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
    <ol class="breadcrumb">
        <li><a href="#">分类管理</a></li>
        <li class="active">分类列表</li>
    </ol>
    <div>
        <div class="row" style="padding: 20px 5px;">
            <form class="form-horizontal">
                <div class="col-xs-12">
                    <div class="form-group">
                        <label class="col-xs-1 control-label">分类名称</label>

                        <div class="col-xs-3">
                            <input type="text" class="form-control" id="nickname" placeholder="请输入分类名称">
                        </div>
                        <div class="col-xs-3">
                            <input type="submit" class="btn btn-primary" value="添 加">
                        </div>
                    </div>
                </div>
            </form>
        </div>

        <div style="height: 35px;background-color: #f5f5f5;line-height: 35px;padding: 0 15px;">
            <i class="fa fa-table" aria-hidden="true"></i>
            标签列表
        </div>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>分类</th>
                <th>文章个数</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>妹子</td>
                <td>10</td>
                <td>
                    <a class="btn btn-danger btn-xs">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        删除
                    </a>
                    |
                    <a class="btn btn-primary btn-xs">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        编辑
                    </a>
                </td>
            </tr>
            <tr>
                <td>Coding</td>
                <td>8</td>
                <td>
                    <a class="btn btn-danger btn-xs">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        删除
                    </a>
                    |
                    <a class="btn btn-primary btn-xs">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        编辑
                    </a>
                </td>
            </tr>
            <tr>
                <td>旅行</td>
                <td>10</td>
                <td>
                    <a class="btn btn-danger btn-xs">
                        <i class="fa fa-times" aria-hidden="true"></i>
                        删除
                    </a>
                    |
                    <a class="btn btn-primary btn-xs">
                        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        编辑
                    </a>
                </td>
            </tr>
            </tbody>
        </table>

        <div class="clearfix">
            <ul class="pagination right" style="margin-top: 0">
                <li><a href="#">&laquo;</a></li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&raquo;</a></li>
            </ul>
        </div>
    </div>


{% endblock %}

{% block js %}

{% endblock %}

EdmureBlog/templates/backend_index.html
{% extends 'backend_layout.html' %}
{% block css %}

{% endblock %}
{% block conent %}
   <h1>欢迎登陆：{{ request.session.user_info.nickname }}</h1>
{% endblock %}

{% block js %}

{% endblock %}

EdmureBlog/templates/backend_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/backend.css"/>
    {% block css %} {% endblock %}
</head>
<body>
<div class="pg-header">
    <div class="logo left" style="text-align: center;background-color: #1c5a9c;">
        <a href="#" style="color: #ffffff;font-size:30px;font-weight: bold;text-decoration: none">
            EasyStack
        </a>
    </div>

    <div class="left-menu left">
        <a class="menu-item" href="/">博客首页</a>
    </div>

    <div class="right-menu right clearfix">

        <div class="user-info right">
            <a href="#" class="avatar">
                <img style="height: 35px" class="img-circle" src="/static/imgs/avatar/123.jpg">
            </a>

            <div class="more-info">
                <a href="/backend/base-info.html" class="more-item">个人信息</a>
                <a href="/logout.html" class="more-item">注销</a>
            </div>
        </div>

        <a class="user-menu right">
            消息
            <i class="fa fa-commenting-o" aria-hidden="true"></i>
            <span class="badge bg-success">2</span>
        </a>

        <a class="user-menu right">
            通知
            <i class="fa fa-envelope-o" aria-hidden="true"></i>
            <span class="badge bg-success">2</span>
        </a>

        <a class="user-menu right">
            任务
            <i class="fa fa-bell-o" aria-hidden="true"></i>
            <span class="badge bg-danger">4</span>
        </a>
    </div>

</div>
<div class="pg-body">
    <div class="menu">
        <a class="menu-item" href="/backend/article-0-0.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>文章管理</span>
        </a>
        <a class="menu-item" href="/backend/category.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>分类管理</span>
        </a>
        <a class="menu-item" href="/backend/tag.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>标签管理</span>
        </a>
        <a class="menu-item" href="/backend/base-info.html">
            <i class="fa fa-cogs" aria-hidden="true"></i>
            <span>个人信息</span>
        </a>
    </div>
    <div class="content">
        {% block conent %} {% endblock %}
    </div>
</div>
<script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
{% block js %}{% endblock %}
</body>
</html>

EdmureBlog/templates/backend_no_article.html
{% extends 'backend_layout.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/plugins/kindeditor/themes/default/default.css"/>
    <style>
        .kind-content {
            width: 100%;
            min-height: 500px;
            visibility: hidden;
        }
    </style>
{% endblock %}

{% block conent %}
    <ol class="breadcrumb" style="margin-bottom: 0;">
        <li><a href="#">文章管理</a></li>
        <li class="active">创建文章</li>
    </ol>
    <div style="padding: 5px 8px;">
        <h3>找不到文章...</h3>
    </div>


{% endblock %}

{% block js %}
    <script charset="utf-8" src="/static/plugins/kindeditor/kindeditor-min.js"></script>
    <script charset="utf-8" src="/static/plugins/kindeditor/lang/zh_CN.js"></script>
    <script>
        var editor;
        KindEditor.ready(function (K) {
            editor = K.create('textarea[name="content"]', {
                resizeType: 1,
                uploadJson: '/on.asp',
                fileManagerJson: '/asp/fjson.asp'
            });
        });
    </script>
{% endblock %}

EdmureBlog/templates/home.html
{% extends 'home_layout.html' %}

{% block content %}

    <div class="summary-list">
        {% for row in article_list %}
            <div class="summary-item">
                <div class="summary-title">
                    <a href="/{{ blog.site }}/{{ row.nid }}.html">{{ row.title }}</a>
                </div>
                <div class="summary-content">
                    {{ row.summary }}
                </div>
                <div class="summary-footer">
                    <span>{{ row.create_time|date:"Y-m-d H:i:s" }}</span>
                    <span>{{ row.user.nickname }}</span>
                    <span>阅读({{ row.read_count }})</span>
                    <a>评论({{ row.comment_count }})</a>
                    <a href="/backend/edit-article-{{ row.nid }}.html">编辑</a>
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}

EdmureBlog/templates/home_layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="/static/plugins/bootstrap/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/plugins/font-awesome/css/font-awesome.css"/>
    <link rel="stylesheet" href="/static/css/edmure.css"/>
    <link rel="stylesheet" href="/static/css/commons.css"/>
    <link rel="stylesheet" href="/static/css/row-avatar.css"/>
    <link rel="stylesheet" href="/static/css/theme/{{ blog.theme }}.css"/>
    {% block css %}{% endblock %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.js"></script>
    <script type="text/javascript" src="/static/plugins/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<div class="pg-header">
    <div class="title">{{ blog.title }}</div>
    <div class="menu-list">
        <a class="menu-item" href="/">首页</a>
        <a class="menu-item" href="/{{ blog.site }}.html">个人首页</a>
        <a class="menu-item" href="/backend/index.html">管理</a>
    </div>
</div>
<div class="pg-body">
    <div class="body-menu">
        <div class="notice">
            <div class="notice-header">公告</div>
            <div class="notice-body">
                <ul>
                    <li>昵称：{{ blog.user.nickname }}</li>
                    <li>粉丝：{{ blog.user.fans.count }}</li>
                    <li>关注：{{ blog.user.f.count }}</li>
                    <li>邮箱：{{ blog.user.email }}</li>
                </ul>
                <div class="memo">
                    真实是人生的命脉，是一切价值的根基。
                </div>
            </div>
        </div>
        <div class="tags">
            <div class="tags-header">标签</div>
            <div class="tags-body">
                <ul>
                    {% for tag in tag_list %}
                        <li><a href="/{{ blog.site }}/tag/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="types">
            <div class="types-header">分类</div>
            <div class="types-body">
                <ul>
                    {% for tag in category_list %}
                        <li><a href="/{{ blog.site }}/category/{{ tag.nid }}.html">{{ tag.title }}({{ tag.article_set.count }})</a></li>
                    {% endfor %}
                </ul>

            </div>
        </div>
        <div class="dates">
            <div class="dates-header">时间</div>
            <div class="dates-body">
                <ul>
                    {% for tag in date_list %}
                        <li><a href="/{{ blog.site }}/date/{{ tag.ctime }}.html">{{ tag.ctime}}({{ tag.num}})</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <div class="body-content">
        {% block content %}{% endblock %}
    </div>
</div>
    {% block js %}{% endblock %}
</body>
</html>

EdmureBlog/templates/home_summary_list.html
{% extends 'home_layout.html' %}

{% block content %}
    <div class="summary-list">
        {% for row in article_list %}
            <div class="summary-item" style="border-bottom: 1px solid #dddddd;padding: 8px 0;">
                <div class="summary-title">
                    <a href="/{{ blog.site }}/{{ row.nid }}.html">{{ row.title }}</a>
                </div>
                <div class="summary-content">
                    {{ row.summary }}
                </div>
                <div class="summary-footer">
                    <span>{{ row.create_time|date:"Y-m-d H:i:s" }}</span>
                    <span>{{ row.user.nickname }}</span>
                    <span>阅读({{ row.read_count }})</span>
                    <a>评论({{ row.comment_count }})</a>
                    <a href="/backend/edit-article-{{ row.nid }}.html">编辑</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}